config/routes.rb
Rails.application.routes.draw do
  root 'lifeguards#index'
  resources :lifeguards do
    resources :sections, only: [:index]
  end
  resources :sections, only: [:index]
end

app/models/lifeguard.rb
class Lifeguard < ActiveRecord::Base
  has_many :sections 
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :lifeguard
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lifeguards_controller.rb
class LifeguardsController < ApplicationController
  before_action :set_lifeguard, only: [:show, :edit, :update, :destroy]

  # GET /lifeguards
  # GET /lifeguards.json
  def index
    @lifeguards = Lifeguard.all
  end

  # GET /lifeguards/1
  # GET /lifeguards/1.json
  def show
  end

  # GET /lifeguards/new
  def new
    @lifeguard = Lifeguard.new
  end

  # GET /lifeguards/1/edit
  def edit
  end

  # POST /lifeguards
  # POST /lifeguards.json
  def create
    @lifeguard = Lifeguard.new(lifeguard_params)

    respond_to do |format|
      if @lifeguard.save
        format.html { redirect_to @lifeguard, notice: 'Lifeguard was successfully created.' }
        format.json { render :show, status: :created, location: @lifeguard }
      else
        format.html { render :new }
        format.json { render json: @lifeguard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lifeguards/1
  # PATCH/PUT /lifeguards/1.json
  def update
    respond_to do |format|
      if @lifeguard.update(lifeguard_params)
        format.html { redirect_to @lifeguard, notice: 'Lifeguard was successfully updated.' }
        format.json { render :show, status: :ok, location: @lifeguard }
      else
        format.html { render :edit }
        format.json { render json: @lifeguard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lifeguards/1
  # DELETE /lifeguards/1.json
  def destroy
    @lifeguard.destroy
    respond_to do |format|
      format.html { redirect_to lifeguards_url, notice: 'Lifeguard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lifeguard
      @lifeguard = Lifeguard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lifeguard_params
      params.require(:lifeguard).permit(:tan, :spf)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    if lifeguard.present?
      @sections = lifeguard.sections
    else
      @sections = Section.all
    end
  end

  private

  def lifeguard
    return nil if params[:lifeguard_id].blank?
    Lifeguard.find(params[:lifeguard_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lifeguards_helper.rb
module LifeguardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LauncherLand</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lifeguards/_form.html.erb
<%= form_for(@lifeguard) do |f| %>
  <% if @lifeguard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lifeguard.errors.count, "error") %> prohibited this lifeguard from being saved:</h2>

      <ul>
      <% @lifeguard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tan %><br>
    <%= f.check_box :tan %>
  </div>
  <div class="field">
    <%= f.label :spf %><br>
    <%= f.number_field :spf %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lifeguards/edit.html.erb
<h1>Editing Lifeguard</h1>

<%= render 'form' %>

<%= link_to 'Show', @lifeguard %> |
<%= link_to 'Back', lifeguards_path %>

app/views/lifeguards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lifeguards</h1>

<table>
  <thead>
    <tr>
      <th>Tan</th>
      <th>Spf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lifeguards.each do |lifeguard| %>
      <tr>
        <td><%= lifeguard.tan %></td>
        <td><%= lifeguard.spf %></td>
        <td><%= link_to 'Show', lifeguard %></td>
        <td><%= link_to 'Edit', edit_lifeguard_path(lifeguard) %></td>
        <td><%= link_to 'Destroy', lifeguard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lifeguard', new_lifeguard_path %>

app/views/lifeguards/new.html.erb
<h1>New Lifeguard</h1>

<%= render 'form' %>

<%= link_to 'Back', lifeguards_path %>

app/views/lifeguards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tan:</strong>
  <%= @lifeguard.tan %>
</p>

<p>
  <strong>Spf:</strong>
  <%= @lifeguard.spf %>
</p>

<%= link_to 'Edit', edit_lifeguard_path(@lifeguard) %> |
<%= link_to 'Back', lifeguards_path %>

app/views/sections/index.html.erb
<ul>
  <% @sections.each do |section| %>
    <li><%= section.name %></li>
  <% end %>
</ul>